name: safe_int_id
description: Uncoordinated unique ID that fits MAX_SAFE_INTEGER on web platform for long enough time.
version: 1.0.0
repository: https://github.com/whyolet/safe_int_id

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
